# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-24 03:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181017_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarimages',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 11, 20, 43, 188000)),
        ),
        migrations.AddField(
            model_name='avatarimages',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 11, 20, 43, 188000)),
        ),
        migrations.AddField(
            model_name='wallpaperimages',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 11, 20, 43, 189000)),
        ),
        migrations.AddField(
            model_name='wallpaperimages',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 11, 20, 43, 189000)),
        ),
    ]
